export const SOC_TOOLTIP_STYLE = {
  backgroundColor: '#161E2E',
  border: '1px solid #1E2D45',
  borderRadius: '6px',
  color: '#C8D8EE',
  fontSize: '12px',
  fontFamily: "'JetBrains Mono', monospace",
};

export const THREAT_SIGNATURES = [
  { id: 'SIG-001', pattern: 'MCP TypeScript SDK has a ReDoS vulnerability', cve: 'CVE-REDOS-MCP-001', severity: 'HIGH' },
  { id: 'SIG-002', pattern: 'MCP TypeScript SDK does not enable DNS rebinding protection by default', cve: 'DNS-REBIND-MCP-002', severity: 'HIGH' },
  { id: 'SIG-003', pattern: 'Cross-Origin MCP Tool Invocation via Empty Default Secret', cve: 'GHSA-j3vx-cx2r-pvg8', severity: 'CRITICAL' },
  { id: 'SIG-004', pattern: 'Network-AI: Unauthenticated Cross-Origin MCP', cve: 'GHSA-j3vx-cx2r-pvg8', severity: 'CRITICAL' },
];

export const COMPLIANCE_FRAMEWORKS: Record<string, Record<string, { title: string; keywords: string[] }>> = {
  'NIST-CSF': {
    'PR.DS-5': { title: 'Protections against data leaks', keywords: ['path', 'traversal', 'filesystem', 'read_file', 'exfil'] },
    'PR.PT-1': { title: 'Audit/log records determined, documented, implemented', keywords: ['semantic', 'prompt', 'injection', 'audit'] },
    'DE.CM-1': { title: 'Network is monitored', keywords: ['chain', 'exfil', 'flow', 'webhook', 'http'] },
    'DE.AE-2': { title: 'Potentially adverse events are analyzed', keywords: ['incident', 'investigator', 'swarm', 'bypass'] },
    'RS.RP-1': { title: 'Response plan executed during/after incident', keywords: ['soar', 'playbook', 'quarantine'] },
  },
  SOC2: {
    'CC6.1': { title: 'Logical access security software, infrastructure, architectures', keywords: ['cost', 'rate', 'limit', 'auth', 'session'] },
    'CC6.7': { title: 'Credentials for infrastructure and software', keywords: ['dpop', 'token', 'credential', 'secret'] },
    'CC7.2': { title: 'Security events are monitored', keywords: ['semantic', 'block', 'flag', 'audit'] },
    'CC8.1': { title: 'Changes to infrastructure and software are authorized', keywords: ['policy', 'copilot', 'tool-integrity', 'rug'] },
  },
  CIS: {
    'CIS-16.11': { title: 'Maintain secure configuration for MCP tool servers', keywords: ['tool', 'integrity', 'schema', 'rug-pull', 'typosquat'] },
    'CIS-13.2': { title: 'Deploy a host-based intrusion detection solution', keywords: ['chain', 'session', 'abuse'] },
    'CIS-10.1': { title: 'Deploy and maintain anti-malware software', keywords: ['semantic', 'threat-lab', 'swarm'] },
  },
  HIPAA: {
    'HIPAA-PHI': { title: 'Block PHI markers in tool arguments', keywords: ['medical record', 'patient ssn', 'diagnosis', 'icd-10', 'prescription'] },
    'HIPAA-AUDIT': { title: 'Policy changes must be audited', keywords: ['audit', 'immutable', 'compliance', 'log'] },
  },
  'PCI-DSS': {
    'PCI-6.4': { title: 'Address common security vulnerabilities in software', keywords: ['injection', 'traversal', 'xss', 'sqli'] },
    'PCI-10.2': { title: 'Implement audit trails to link access to individual users', keywords: ['audit', 'trail', 'session', 'identity'] },
  },
};

export const SOAR_PLAYBOOKS = [
  {
    name: 'high-confidence-semantic-run',
    severity: 'HIGH',
    when: [
      { field: 'event', op: 'eq', value: 'semantic_flag' },
      { field: 'confidence', op: 'gte', value: 0.9 },
      { field: 'toolName', op: 'contains', value: 'run' },
    ],
    actions: [
      { type: 'notify', severity: 'high', message: 'High-confidence semantic flag on run tool' },
      { type: 'open', detail: 'open_threat_lab' },
      { type: 'suggest', detail: 'suggest_policy_block' },
    ],
  },
  {
    name: 'tool-integrity-critical',
    severity: 'CRITICAL',
    when: [
      { field: 'event', op: 'eq', value: 'tool_integrity' },
      { field: 'severity', op: 'eq', value: 'critical' },
    ],
    actions: [
      { type: 'notify', severity: 'critical', message: 'Tool integrity critical — possible rug pull' },
      { type: 'pagerduty', detail: 'page-on-call-sre' },
    ],
  },
  {
    name: 'credential-exfil-auto-block',
    severity: 'CRITICAL',
    when: [
      { field: 'category', op: 'eq', value: 'credential-exfil' },
      { field: 'confidence', op: 'gte', value: 0.95 },
    ],
    actions: [
      { type: 'notify', severity: 'critical', message: 'Credential exfiltration attempt detected' },
      { type: 'suggest', detail: 'auto-block-rule-add' },
      { type: 'pagerduty', detail: 'page-security-team' },
    ],
  },
  {
    name: 'ssrf-cloud-metadata-alert',
    severity: 'HIGH',
    when: [
      { field: 'category', op: 'eq', value: 'ssrf-evasion' },
      { field: 'hint', op: 'contains', value: 'metadata' },
    ],
    actions: [
      { type: 'notify', severity: 'high', message: 'SSRF cloud metadata access attempt' },
      { type: 'open', detail: 'open_threat_lab' },
    ],
  },
];

export const ATTACK_SCENARIOS = [
  {
    id: 'SCN-A',
    name: 'Credential Exfiltration',
    stage1Acc: 85,
    stage2Acc: 96,
    blockRate: 95.4,
    confidence: 0.95,
    latency1: 280,
    latency2: 104,
    requests: 29100,
    blocked: 27762,
    color: '#FF4D6A',
    timeline: [
      { t: 0, acc: 85, conf: 0.8 },
      { t: 15, acc: 88, conf: 0.83 },
      { t: 30, acc: 91, conf: 0.87 },
      { t: 45, acc: 94, conf: 0.91 },
      { t: 60, acc: 96, conf: 0.95 },
    ],
    description: 'SSH key and cloud credential reads via path traversal',
  },
  {
    id: 'SCN-B',
    name: 'Lateral Movement',
    stage1Acc: 82,
    stage2Acc: 92,
    blockRate: 93.1,
    confidence: 0.92,
    latency1: 310,
    latency2: 118,
    requests: 28500,
    blocked: 26543,
    color: '#F5A623',
    timeline: [
      { t: 0, acc: 82, conf: 0.77 },
      { t: 15, acc: 85, conf: 0.8 },
      { t: 30, acc: 88, conf: 0.84 },
      { t: 45, acc: 91, conf: 0.89 },
      { t: 60, acc: 92, conf: 0.92 },
    ],
    description: 'Multi-tool attack chains designed to pivot through system access',
  },
  {
    id: 'SCN-C',
    name: 'Prompt Injection Wave',
    stage1Acc: 88,
    stage2Acc: 97,
    blockRate: 96.8,
    confidence: 0.93,
    latency1: 245,
    latency2: 95,
    requests: 31200,
    blocked: 30197,
    color: '#4B9EFF',
    timeline: [
      { t: 0, acc: 88, conf: 0.82 },
      { t: 15, acc: 91, conf: 0.86 },
      { t: 30, acc: 93, conf: 0.89 },
      { t: 45, acc: 95, conf: 0.92 },
      { t: 60, acc: 97, conf: 0.93 },
    ],
    description: 'Zero-width character and unicode homoglyph injection attacks',
  },
  {
    id: 'SCN-D',
    name: 'SSRF Cloud Metadata',
    stage1Acc: 90,
    stage2Acc: 98,
    blockRate: 97.2,
    confidence: 0.97,
    latency1: 198,
    latency2: 88,
    requests: 22400,
    blocked: 21773,
    color: '#00D67C',
    timeline: [
      { t: 0, acc: 90, conf: 0.85 },
      { t: 15, acc: 93, conf: 0.89 },
      { t: 30, acc: 95, conf: 0.92 },
      { t: 45, acc: 97, conf: 0.95 },
      { t: 60, acc: 98, conf: 0.97 },
    ],
    description: 'AWS/GCP metadata endpoint access via decimal/hex IP encoding',
  },
  {
    id: 'SCN-E',
    name: 'SQL/NoSQL Injection',
    stage1Acc: 86,
    stage2Acc: 94,
    blockRate: 94.6,
    confidence: 0.94,
    latency1: 255,
    latency2: 102,
    requests: 18900,
    blocked: 17879,
    color: '#8B7FFF',
    timeline: [
      { t: 0, acc: 86, conf: 0.81 },
      { t: 15, acc: 89, conf: 0.85 },
      { t: 30, acc: 91, conf: 0.88 },
      { t: 45, acc: 93, conf: 0.92 },
      { t: 60, acc: 94, conf: 0.94 },
    ],
    description: 'Parameterized bypass, comment injection, MongoDB $where operator',
  },
  {
    id: 'SCN-F',
    name: 'Tool Integrity / Rug Pull',
    stage1Acc: 80,
    stage2Acc: 89,
    blockRate: 91.3,
    confidence: 0.88,
    latency1: 340,
    latency2: 148,
    requests: 14300,
    blocked: 13051,
    color: '#FF8C42',
    timeline: [
      { t: 0, acc: 80, conf: 0.75 },
      { t: 15, acc: 83, conf: 0.79 },
      { t: 30, acc: 85, conf: 0.82 },
      { t: 45, acc: 87, conf: 0.85 },
      { t: 60, acc: 89, conf: 0.88 },
    ],
    description: 'Schema mutation detection for tool description rug-pull attempts',
  },
];
